[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_vault_swap = "3haUA3nngbCdg6XH8PbBKg1rXo4a6Q44ak8fabbC7L9j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "AutGVHhzZadcs73W5V5TgPY3DiiEu4cgwv63YywjyHvQ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
